export const ModalData = [
  {
    id: "0",
    Name: "Rabia ",
    Contact: "+92309874556",
    Project: "LDA City",
    Budget: "400 PKR",
    Toc: "04:00 PM",
    Source: "News Paper",
    Country: "Pakistan",
    Status: "new",
    Interest: "5 Marla",
    Allocate: "Rabia",
    Task: "Sale",
    Deadline: "05/06/2021",
    Returned: "----",
  },
  {
    id: "1",
    Name: "Atif ",
    Contact: "+92309874556",
    Project: "LDA City",
    Budget: "400 PKR",
    Toc: "04:00 PM",
    Source: "News Paper",
    Country: "Pakistan",
    Status: "new",
    Interest: "5 Marla",
    Allocate: "Rabia",
    Task: "Sale",
    Deadline: "05/06/2021",
    Returned: "Qasim",
  },
  {
    id: "2",
    Name: "Ali ",
    Contact: "+92309874556",
    Project: "LDA City",
    Budget: "400 PKR",
    Toc: "04:00 PM",
    Source: "News Paper",
    Country: "Pakistan",
    Status: "new",
    Interest: "5 Marla",
    Allocate: "Rabia",
    Task: "Sale",
    Deadline: "05/06/2021",
    Returned: "----",
  },
  {
    id: "3",
    Name: "Qasim ",
    Contact: "+92309874556",
    Project: "LDA City",
    Budget: "400 PKR",
    Toc: "04:00 PM",
    Source: "News Paper",
    Country: "Pakistan",
    Status: "new",
    Interest: "5 Marla",
    Allocate: "Rabia",
    Task: "Sale",
    Deadline: "05/06/2021",
    Returned: "Ali",
  },
  {
    id: "4",
    Name: "Imtesal ",
    Contact: "+92309874556",
    Project: "LDA City",
    Budget: "400 PKR",
    Toc: "04:00 PM",
    Source: "News Paper",
    Country: "Pakistan",
    Status: "new",
    Interest: "5 Marla",
    Allocate: "Rabia",
    Task: "Sale",
    Deadline: "05/06/2021",
    Returned: "Ahmed",
  },
  {
    id: "5",
    Name: "sana ",
    Contact: "+92309874556",
    Project: "LDA City",
    Budget: "400 PKR",
    Toc: "04:00 PM",
    Source: "News Paper",
    Country: "Pakistan",
    Status: "new",
    Interest: "5 Marla",
    Allocate: "Rabia",
    Task: "Sale",
    Deadline: "05/06/2021",
    Returned: "Sana",
  },
];