export const LeadsData = [
  {
    id: "0",
    Name: "Rabia ",
    Contact: "+92309874556",
    Project: "LDA City",
    Budget: "400 PKR",
    Toc: "04:00 PM",
    Country: "Pakistan",
    Status: "new",
    Interest: "5 Marla",
    Allocate: "Rabia",
    Email:"rabia@gmail.com",
    Task: "Sale",
    Deadline: "05/06/2021",
  },
  {
    id: "1",
    Name: "Atif ",
    Contact: "+92309874556",
    Project: "LDA City",
    Budget: "400 PKR",
    Toc: "04:00 PM",
    Country: "Pakistan",
    Status: "new",
    Interest: "5 Marla",
    Allocate: "Rabia",
    Email:"rabia@gmail.com",
    Task: "Sale",
    Deadline: "05/06/2021"
  },
  {
    id: "2",
    Name: "Ali ",
    Contact: "+92309874556",
    Project: "LDA City",
    Budget: "400 PKR",
    Toc: "04:00 PM",
    Country: "Pakistan",
    Status: "new",
    Interest: "5 Marla",
    Allocate: "Rabia",
    Email:"rabia@gmail.com",
    Task: "Sale",
    Deadline: "05/06/2021"
  },
  {
    id: "3",
    Name: "Qasim ",
    Contact: "+92309874556",
    Project: "LDA City",
    Budget: "400 PKR",
    Toc: "04:00 PM",
    Country: "Pakistan",
    Status: "new",
    Interest: "5 Marla",
    Allocate: "Rabia",
    Email:"rabia@gmail.com",
    Task: "Sale",
    Deadline: "05/06/2021"
  },
  {
    id: "4",
    Name: "Imtesal ",
    Contact: "+92309874556",
    Project: "LDA City",
    Budget: "400 PKR",
    Toc: "04:00 PM",
    Country: "Pakistan",
    Status: "new",
    Interest: "5 Marla",
    Allocate: "Rabia",
    Email:"rabia@gmail.com",
    Task: "Sale",
    Deadline: "05/06/2021"
  },
  {
    id: "5",
    Name: "sana ",
    Contact: "+92309874556",
    Project: "LDA City",
    Budget: "400 PKR",
    Toc: "04:00 PM",
    Country: "Pakistan",
    Status: "new",
    Interest: "5 Marla",
    Allocate: "Rabia",
    Email:"rabia@gmail.com",
    Task: "Sale",
    Deadline: "05/06/2021",
  },
];
