export const ModalData = [
  {
    id: "0",
    Name: "Rabia 0",
    Last_Name: "waheed",
    Email: "Rabia@gmail.com",
    Gender: "Female",
    Contact: "+92309874556",
    Type: "Employee",
    Password: "12345",
  },
  {
    id: "1",
    Name: "Rabia 1",
    Last_Name: "waheed",
    Email: "Rabia@gmail.com",
    Gender: "Female",
    Contact: "+92309874556",
    Type: "Employee",
    Password: "12345",
  },
  {
    id: "2",
    Name: "Rabia 2",
    Last_Name: "waheed",
    Email: "Rabia@gmail.com",
    Gender: "Female",
    Contact: "+92309874556",
    Type: "Employee",
    Password: "12345",
  },
  {
    id: "3",
    Name: "Rabia 3",
    Last_Name: "waheed",
    Email: "Rabia@gmail.com",
    Gender: "Female",
    Contact: "+92309874556",
    Type: "Employee",
    Password: "12345",
  },
  {
    id: "4",
    Name: "Rabia 4",
    Last_Name: "waheed",
    Email: "Rabia@gmail.com",
    Gender: "Female",
    Contact: "+92309874556",
    Type: "Employee",
    Password: "12345",
  },
  {
    id: "5",
    Name: "Rabia 5",
    Last_Name: "waheed",
    Email: "Rabia@gmail.com",
    Gender: "Female",
    Contact: "+92309874556",
    Type: "Employee",
    Password: "12345",
  },
  {
    id: "6",
    Name: "Rabia 6",
    Last_Name: "waheed",
    Email: "Rabia@gmail.com",
    Gender: "Female",
    Contact: "+92309874556",
    Type: "Employee",
    Password: "12345",
  },
  {
    id: "3",
    Name: "sana",
    Last_Name: "waheed",
    Email: "sana@gmail.com",
    Gender: "Female",
    Contact: "+92309874556",
    Type: "Employee",
    Password: "12345",
  },
];
