export const ProjectListData = [
  {
    id: "1",
    Name: "LDA",
    Units: "10",
    inventory: [
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
    ],
  },
  {
    id: "2",
    Name: "DHA",
    Units: "20",
    inventory: [
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
    ],
  },
  {
    id: "3",
    Name: "Pak Arab",
    Units: "25",
    inventory: [
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
    ],
  },
  {
    id: "4",
    Name: "Bahria",
    Units: "5",
    inventory: [
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
    ],
  },
  {
    id: "5",
    Name: "PCSIR",
    Units: "15",
    inventory: [
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
      {
        name: "inventory 1",
        blockName: "A1",
        status: "open",
        category: "rent",
      },
    ],
  },
];
